name: matnbaz_mobile
description: The mobile app for matnbaz.net

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  graphql_flutter: ^5.0.0
  json_annotation: ^4.3.0
  equatable: ^2.0.3
  gql: ^0.13.1-alpha
  pull_to_refresh: ^2.0.0
  flutter_html: ^2.2.1

  cupertino_icons: ^1.0.2

# Temporary:
dependency_overrides:
  gql_exec: 0.3.0
  gql_link: 0.4.0
  gql_http_link: 0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  artemis: '>=7.0.0 <8.0.0'
  build_runner: ^2.1.4
  json_serializable: ^6.0.1
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpg

  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir-Black.ttf
          weight: 900
        - asset: assets/fonts/Vazir-Bold.ttf
          weight: 700
        - asset: assets/fonts/Vazir-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazir-Regular.ttf
          weight: 400
        - asset: assets/fonts/Vazir-Light.ttf
          weight: 300
        - asset: assets/fonts/Vazir-Thin.ttf
          weight: 100
    - family:  MatnbazCustomIcons
      fonts:
      - asset: assets/fonts/MatnbazCustomIcons.ttf

